import adapter from '@sveltejs/adapter-cloudflare';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
	plugins: [
		sveltekit({
			compilerOptions: {
				// Force runes mode for the project, except for libraries. Can be removed in svelte 6.
				runes: ({ filename }) =>
					filename.split(/[/\\]/).includes('node_modules') ? undefined : true
			},
			adapter: adapter()
		}),
		VitePWA({
			registerType: 'autoUpdate',
			// injectManifest (not generateSW) since M4 needs a hand-written 'push'
			// event listener to actually display reminders — generateSW's
			// Workbox-authored service worker has no hook for custom event
			// listeners, only caching recipes. src/sw.ts owns both the
			// caching rules (moved there from workbox.runtimeCaching below) and the
			// push/notificationclick handlers.
			strategies: 'injectManifest',
			srcDir: 'src',
			// Deliberately NOT `service-worker.ts` — that exact filename is
			// SvelteKit's own reserved convention (kit.files.serviceWorker) for its
			// unrelated native service-worker feature, and having both present
			// would fight over registering/serving a service worker.
			filename: 'sw.ts',
			includeAssets: ['pictograms.svg'],
			manifest: {
				id: '/today',
				name: 'MedsAssist',
				short_name: 'MedsAssist',
				lang: 'en',
				dir: 'ltr',
				orientation: 'portrait',
				description: 'What to take, right now — with a photo of the actual pill.',
				start_url: '/today',
				scope: '/',
				display: 'standalone',
				background_color: '#FAF9F6', // --ground
				theme_color: '#0F5D4E', // --sage-700
				categories: ['medical', 'health', 'lifestyle'],
				// A reminder tap reuses an already-open window instead of stacking
				// a second instance of the app.
				launch_handler: { client_mode: 'navigate-existing' },
				icons: [
					{ src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
					{ src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
					{
						src: '/icons/icon-512-maskable.png',
						sizes: '512x512',
						type: 'image/png',
						purpose: 'maskable'
					}
				],
				// What upgrades Chromium's mini-infobar into the rich install
				// dialog. Both narrow entries MUST share one aspect ratio or
				// Chromium silently drops the whole set. Generated by
				// scripts/capture-screenshots.mjs; `label` is read aloud by screen
				// readers, so these are sentences rather than filenames.
				screenshots: [
					{
						src: '/screenshots/today-narrow.png',
						sizes: '780x1688',
						type: 'image/png',
						form_factor: 'narrow',
						label: "Today's doses, each with a photo of the actual pill"
					},
					{
						src: '/screenshots/medicines-narrow.png',
						sizes: '780x1688',
						type: 'image/png',
						form_factor: 'narrow',
						label: 'Your medicine list, with how many days of supply are left'
					},
					{
						src: '/screenshots/today-wide.png',
						sizes: '1920x1080',
						type: 'image/png',
						form_factor: 'wide',
						label: "Today's doses on a larger screen"
					}
				],
				shortcuts: [
					{
						name: 'Add a medicine',
						short_name: 'Add',
						url: '/medicines/add',
						icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }]
					}
				]
			},
			injectManifest: {
				// Default globPatterns also match static/pictograms.svg and the icon
				// PNGs, which is what we want precached alongside the JS/CSS bundle.
				maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
				// The install-dialog screenshots and the landing hero are ~450 KB
				// that every installed user would otherwise download into the
				// precache and never see again — the install dialog reads them
				// from the network before the app is installed at all.
				globIgnores: ['**/screenshots/**', '**/marketing/**']
			}
		})
	]
});
